#!/usr/bin/env bash

main() {
  selection=$(multidisplay_menu | rofi -p monitor -dmenu -i -lines 5)
  echo "$selection"

  case "$selection" in
  *"landscape"*)
    multidisplayctl --mode join-landscape
    ;;
  *"portrait"*)
    multidisplayctl --mode join-portrait
    ;;
  *"Duplicate"*)
    multidisplayctl --mode duplicate
    ;;
  *"Single"*)
    multidisplayctl --mode single
    ;;
  esac
}

multidisplay_menu() {
  echo -en "Join (landscape)\\0icon\\x1fpreferences-desktop-display\\n"
  echo -en "Join (portrait)\\0icon\\x1fpreferences-desktop-display\\n"
  echo -en "Duplicate\\0icon\\x1fpreferences-desktop-display\\n"
  echo -en "Single\\0icon\\x1fpreferences-desktop-display\\n"
}

main
