#!/usr/bin/env bash

main() {
  selection=$(power_menu | rofi -p power -dmenu -i -lines 5)

  case "$selection" in
  *"Lock"*)
    betterlockscreen -l dim
    ;;
  *"Log"*)
    loginctl terminate-session "$XDG_SESSION_ID"
    ;;
  *"Suspend"*)
    systemctl suspend
    ;;
  *"Reboot"*)
    systemctl reboot
    ;;
  *"Shutdown"*)
    systemctl poweroff
    ;;
  esac
}

power_menu() {
  echo -en "Lock screen\\0icon\\x1fsystem-lock-screen\\n"
  echo -en "Log out\\0icon\\x1fsystem-log-out\\n"
  echo -en "Suspend\\0icon\\x1fsystem-suspend\\n"
  echo -en "Reboot\\0icon\\x1fsystem-reboot\\n"
  echo -en "Shutdown\\0icon\\x1fsystem-shutdown\\n"
}

main
