#!/bin/bash

source "$HOME/.config/bspwm/init"

# kill
killall sxhkd
killall picom
killall dunst

# autostart
# xss-lock -l -- betterlockscreen --lock dimblur &
sxhkd &
picom --experimental-backends &
dunst &
feh --recursive --randomize --bg-fill "$DE_WALLPAPERS" &

# monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# window config
bspc config border_width 1
bspc config window_gap 10

# layout config
bspc config split_ratio 0.5
bspc config automatic_scheme longest_side
bspc config borderless_monocle true
bspc config gapless_monocle true

# mouse config
bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action2 move
bspc config click_to_focus button1
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# color config
bspc config normal_border_color "#1F2430"
bspc config focused_border_color "#FFCC66"
bspc config presel_feedback_color "#FFEE99"

# rules
bspc rule -a '*:nemo' state=floating center=true
bspc rule -a Lxappearance state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
