#!/bin/bash

source "$HOME/.config/bspwm/init"

# monitor
monitorList=($(bspc query -M --names))

if [[ ${#monitorList[@]} == 1 ]]; then
  bspc monitor -d I II III IV V
elif [[ ${#monitorList[@]} == 2 ]]; then
  bspc monitor "${monitorList[1]}" -d I II III IV V
  bspc monitor "${monitorList[2]}" -d VI VII VIII IX X
else
  for monitor in $(bspc query -M); do
    bspc monitor "$monitor" -d I II III IV V
  done
fi
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# window config
bspc config border_width 1
bspc config window_gap 10

# layout config
bspc config split_ratio 0.5
bspc config automatic_scheme longest_side
bspc config borderless_monocle true
bspc config gapless_monocle true

# mouse config
bspc config click_to_focus button1
bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# color config
bspc config normal_border_color "#1F2430"
bspc config focused_border_color "#FFCC66"
bspc config presel_feedback_color "#FFEE99"

# rules
bspc rule -a Lxappearance state=floating
bspc rule -a zoom state=floating follow=on

feh --recursive --randomize --bg-fill "$DE_WALLPAPERS" &

# kill
killall sxhkd
killall picom
killall dunst
while pgrep -x picom >/dev/null; do sleep 0.001; done

# autostart
# xss-lock -l -- betterlockscreen --lock dimblur &
sxhkd &
picom --experimental-backends &
dunst &

vpn_status=$(nordvpn status | head -n 1 | awk -F ': ' '{print $2}')
if [[ "$vpn_status" != "Connected" ]]; then
  notify-send "NordVPN connecting..."
  nordvpn c -g Double_VPN &
else
  notify-send "NordVPN is already connected!"
fi
