#!/bin/bash

#export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_FONT_DPI=96

export DE_CONFIGS_DIR="$(
  cd "$(dirname "$0")"
  pwd -P
)/../"

export PATH="$DE_CONFIGS_DIR/bin:$DE_CONFIGS_DIR/rofi/scripts:$PATH"

#
# Environment variables
#

export DE_TERM_EMULATOR="alacritty"
export TERMINAL="kitty"
export DE_BROWSER="firefox-developer-edition"

export DE_WALLPAPERS="$DE_CONFIGS_DIR/wallpapers"

#
# Icons
#

export DE_ICON_VOLUME=""
export DE_ICON_MUTE=""
export DE_ICON_CLOCK=""
export DE_ICON_CALENDAR=""
export DE_ICON_VPN=""
export DE_ICON_BATTERY=""
export DE_ICON_ADAPTER=""
